export const breeders = [
  "Dainichi Toyota",
  "Dainichi",
  "Hidemassa",
  "Hiroi",
  "Hoshikin",
  "Isa",
  "Izumiya",
  "Kondo",
  "Mano",
  "Marudo",
  "Maruhiro",
  "Marusei",
  "Momotaro",
  "Nagoshi",
  "Nogami",
  "Ogata",
  "Okawa",
  "Omosako",
  "Oya",
  "SFF",
  "Sekiguchi",
  "Tanaka",
  "Taniguchi",
  "Torazo",
  "Yagenji",
  "Yoshikigoi",
];

export const varieties = [
  "Asagi",
  "Benigoi",
  "Chagoi",
  "Goromo",
  "Goshiki",
  "Karashigoi",
  "Kohaku",
  "Mukashi Ogon",
  "Ochiba",
  "Sanke",
  "Shiro-utsuri",
  "Showa",
  "Shusui",
  "Soragoi",
  "Yamabuki Ogon",
];
export const varietiesColor = [
  { title: "Asagi", color: "#C5CAE9" },
  { title: "Benigoi", color: "#B71C1C" },
  { title: "Chagoi", color: "#3E2723" },
  { title: "Goromo", color: "#D1C4E9" },
  { title: "Goshiki", color: "#B2DFDB" },
  { title: "Karashigoi", color: "#FFB74D" },
  { title: "Kohaku", color: "#F57F17" },
  { title: "Mukashi Ogon", color: "#B2EBF2" },
  { title: "Ochiba", color: "#E0E0E0" },
  { title: "Sanke", color: "#FFE082" },
  { title: "Shiro-utsuri", color: "#BBDEFB" },
  { title: "Showa", color: "#0C4184" },
  { title: "Shusui", color: "#B3E5FC" },
  { title: "Soragoi", color: "#E0E0E0" },
  { title: "Yamabuki Ogon", color: "#F3E5F5" },
];

export const bloodlines = [
  "BigBang",
  "Black Panda",
  "BlackBudo",
  "BlackDiamondX",
  "Botan",
  "DMJr",
  "DMM",
  "DSKohaku",
  "Dragon",
  "G Mako",
  "GachaDX",
  "Golden Corn",
  "Hourai",
  "Isa",
  "Izumiya",
  "J. Butterfly",
  "Kinsen",
  "M-Sanke",
  "MSankeJr",
  "Mako",
  "Marusaka",
  "Momoiro",
  "MonaLisa",
  "NewMiharaX",
  "Omosako",
  "Othello",
  "Oya",
  "Panda No3",
  "SP.Butta",
  "Sakai",
  "Stardust",
  "Super Mako",
  "Super Mango",
  "SuperKohaku",
  "SuperMonster",
  "Taiho",
  "Tanaka",
  "WhiteX",
  "XGinrin",
];

export const skinTypes = ["Scaled", "Ginrin", "Doitsu"];

export const sex = ["Male", "Female", "Unknown"];
